    ticks_per_revolution: 148000
    baseline: 0.462002

    left_wheel_circ: 0.77411356258
    right_wheel_circ: 0.76026542216

    kp_left: 180
    ki_left: 200
    kd_left: 0

    kp_right: 190
    ki_right: 195
    kd_right: 0

    kp_cross: 0
    ki_cross: 0
    kd_cross: 0
